# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1163, 600)
        MainWindow.setMinimumSize(QtCore.QSize(900, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.widget_4.setFont(font)
        self.widget_4.setObjectName("widget_4")
        self.label_8 = QtWidgets.QLabel(self.widget_4)
        self.label_8.setGeometry(QtCore.QRect(20, 0, 66, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget_4)
        self.label_9.setGeometry(QtCore.QRect(90, 0, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget_4)
        self.label_10.setGeometry(QtCore.QRect(160, 0, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.widget_4)
        self.label_11.setGeometry(QtCore.QRect(220, 0, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        self.label_5.setGeometry(QtCore.QRect(250, 0, 66, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget_4)
        self.label_6.setGeometry(QtCore.QRect(320, 0, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_4)
        self.label_7.setGeometry(QtCore.QRect(350, 0, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.widget_4, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.qwtPlot = QwtPlot(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlot.sizePolicy().hasHeightForWidth())
        self.qwtPlot.setSizePolicy(sizePolicy)
        self.qwtPlot.setMinimumSize(QtCore.QSize(200, 200))
        self.qwtPlot.setMaximumSize(QtCore.QSize(10000, 1000))
        self.qwtPlot.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.qwtPlot.setObjectName("qwtPlot")
        self.gridLayout_4.addWidget(self.qwtPlot, 0, 0, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setEnabled(True)
        self.textBrowser_2.setMinimumSize(QtCore.QSize(50, 0))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_4.addWidget(self.textBrowser_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(100, 0))
        self.textBrowser.setMaximumSize(QtCore.QSize(1000, 80))
        self.textBrowser.setBaseSize(QtCore.QSize(0, 0))
        self.textBrowser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textBrowser.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.textBrowser)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(1000, 80))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout.addWidget(self.plainTextEdit)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setMaximumSize(QtCore.QSize(200, 80))
        self.widget_2.setObjectName("widget_2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 16, 64, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.spinBox = QtWidgets.QSpinBox(self.widget_2)
        self.spinBox.setGeometry(QtCore.QRect(75, 10, 60, 27))
        self.spinBox.setMaximum(31557600)
        self.spinBox.setSingleStep(10)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget_2)
        self.spinBox_2.setGeometry(QtCore.QRect(140, 10, 60, 27))
        self.spinBox_2.setMaximum(31557600)
        self.spinBox_2.setSingleStep(10)
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.widget_2)
        self.spinBox_3.setGeometry(QtCore.QRect(140, 40, 60, 27))
        self.spinBox_3.setMinimum(-10000000)
        self.spinBox_3.setMaximum(10000000)
        self.spinBox_3.setSingleStep(10)
        self.spinBox_3.setObjectName("spinBox_3")
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 40, 97, 22))
        self.checkBox_3.setObjectName("checkBox_3")
        self.spinBox_4 = QtWidgets.QSpinBox(self.widget_2)
        self.spinBox_4.setGeometry(QtCore.QRect(75, 40, 60, 27))
        self.spinBox_4.setMinimum(-10000000)
        self.spinBox_4.setMaximum(10000000)
        self.spinBox_4.setSingleStep(10)
        self.spinBox_4.setObjectName("spinBox_4")
        self.radioButton = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton.setGeometry(QtCore.QRect(10, 10, 101, 22))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 30, 116, 22))
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 50, 116, 22))
        self.radioButton_3.setChecked(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.widget_2)
        self.gridLayout_4.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 1, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(299, 20))
        self.widget.setMaximumSize(QtCore.QSize(400, 80))
        self.widget.setObjectName("widget")
        self.pushButton_cal = QtWidgets.QPushButton(self.widget)
        self.pushButton_cal.setGeometry(QtCore.QRect(0, 0, 70, 20))
        self.pushButton_cal.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_cal.setFont(font)
        self.pushButton_cal.setObjectName("pushButton_cal")
        self.checkBox_logY = QtWidgets.QCheckBox(self.widget)
        self.checkBox_logY.setGeometry(QtCore.QRect(100, 0, 119, 22))
        self.checkBox_logY.setObjectName("checkBox_logY")
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setGeometry(QtCore.QRect(240, 0, 151, 22))
        self.checkBox.setObjectName("checkBox")
        self.spinBox_5 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_5.setGeometry(QtCore.QRect(330, 0, 71, 21))
        self.spinBox_5.setToolTip("")
        self.spinBox_5.setMinimum(2)
        self.spinBox_5.setMaximum(5000)
        self.spinBox_5.setProperty("value", 10)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(391, 0))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -508, 375, 2000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 2000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 371, 1601))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(4)
        self.gridLayout_2.setVerticalSpacing(11)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1163, 22))
        self.menubar.setObjectName("menubar")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuUtilities = QtWidgets.QMenu(self.menubar)
        self.menuUtilities.setObjectName("menuUtilities")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCal_Mode = QtWidgets.QAction(MainWindow)
        self.actionCal_Mode.setCheckable(True)
        self.actionCal_Mode.setAutoRepeat(False)
        self.actionCal_Mode.setObjectName("actionCal_Mode")
        self.actionNon_Cal_Mode = QtWidgets.QAction(MainWindow)
        self.actionNon_Cal_Mode.setCheckable(True)
        self.actionNon_Cal_Mode.setChecked(True)
        self.actionNon_Cal_Mode.setAutoRepeat(False)
        self.actionNon_Cal_Mode.setObjectName("actionNon_Cal_Mode")
        self.actionSet_time = QtWidgets.QAction(MainWindow)
        self.actionSet_time.setObjectName("actionSet_time")
        self.actionTerminal_Mode = QtWidgets.QAction(MainWindow)
        self.actionTerminal_Mode.setCheckable(True)
        self.actionTerminal_Mode.setAutoRepeat(False)
        self.actionTerminal_Mode.setObjectName("actionTerminal_Mode")
        self.actionSet_Nozzle_Size = QtWidgets.QAction(MainWindow)
        self.actionSet_Nozzle_Size.setObjectName("actionSet_Nozzle_Size")
        self.actionNotes = QtWidgets.QAction(MainWindow)
        self.actionNotes.setObjectName("actionNotes")
        self.actionSet_Other_Parameters = QtWidgets.QAction(MainWindow)
        self.actionSet_Other_Parameters.setObjectName("actionSet_Other_Parameters")
        self.menuView.addAction(self.actionCal_Mode)
        self.menuView.addAction(self.actionNon_Cal_Mode)
        self.menuView.addAction(self.actionTerminal_Mode)
        self.menuUtilities.addAction(self.actionSet_time)
        self.menuUtilities.addAction(self.actionSet_Other_Parameters)
        self.menuUtilities.addAction(self.actionNotes)
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuUtilities.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setToolTip(_translate("MainWindow", "more info about this"))
        self.label_8.setText(_translate("MainWindow", "Capture"))
        self.label_9.setToolTip(_translate("MainWindow", "more info about this"))
        self.label_9.setText(_translate("MainWindow", "Value"))
        self.label_10.setToolTip(_translate("MainWindow", "more info about this"))
        self.label_10.setText(_translate("MainWindow", "Scale"))
        self.label_11.setToolTip(_translate("MainWindow", "more info about this"))
        self.label_11.setText(_translate("MainWindow", "Plot"))
        self.label_5.setToolTip(_translate("MainWindow", "more info about this"))
        self.label_5.setText(_translate("MainWindow", "Refrence"))
        self.label_6.setToolTip(_translate("MainWindow", "more info about this"))
        self.label_6.setText(_translate("MainWindow", "Zero"))
        self.label_7.setToolTip(_translate("MainWindow", "more info about this"))
        self.label_7.setText(_translate("MainWindow", "Span"))
        self.checkBox_2.setText(_translate("MainWindow", "X range"))
        self.checkBox_3.setText(_translate("MainWindow", "Y range"))
        self.radioButton.setText(_translate("MainWindow", "LF only"))
        self.radioButton_2.setText(_translate("MainWindow", "RTN only"))
        self.radioButton_3.setText(_translate("MainWindow", "RTN and LF"))
        self.pushButton_cal.setText(_translate("MainWindow", "Calibrate"))
        self.checkBox_logY.setText(_translate("MainWindow", "logarithmic Y"))
        self.checkBox.setText(_translate("MainWindow", "Tail Data"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuUtilities.setTitle(_translate("MainWindow", "Utilities"))
        self.actionCal_Mode.setText(_translate("MainWindow", "Cal Mode"))
        self.actionNon_Cal_Mode.setText(_translate("MainWindow", "Non Cal Mode"))
        self.actionSet_time.setText(_translate("MainWindow", "Set time"))
        self.actionTerminal_Mode.setText(_translate("MainWindow", "Terminal Mode"))
        self.actionSet_Nozzle_Size.setText(_translate("MainWindow", "Set Nozzle Size"))
        self.actionNotes.setText(_translate("MainWindow", "Notes"))
        self.actionSet_Other_Parameters.setText(_translate("MainWindow", "Set Other Parameters"))
from qwt_plot import QwtPlot


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
